baseURL: https://dcs550practice.netlify.app
title: DCS 550 Practice Blog
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Josh Howard
  description:  Christ-follower, UNC Grad, Coach, Teacher, Proud Husband and Dad
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/jhoward2122
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio
